doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        mapping_types:
            enum: string
        types:
            # Common
            datetime: App\Common\Infrastructure\Doctrine\Type\DateTimeType
            email: App\Common\Infrastructure\Doctrine\Type\EmailType
            # Question
            profile_id: App\Question\Infrastructure\Doctrine\Type\ProfileIdType
            question_id: App\Question\Infrastructure\Doctrine\Type\QuestionIdType
            internal_name: App\Question\Infrastructure\Doctrine\Type\InternalNameType
            display_name: App\Question\Infrastructure\Doctrine\Type\DisplayNameType
            question_type: App\Question\Infrastructure\Doctrine\Type\QuestionTypeType
            question_presentation: App\Question\Infrastructure\Doctrine\Type\QuestionPresentationType
            option_id: App\Question\Infrastructure\Doctrine\Type\OptionIdType
            option_value: App\Question\Infrastructure\Doctrine\Type\OptionValueType
            option_label: App\Question\Infrastructure\Doctrine\Type\OptionLabelType
            option_order: App\Question\Infrastructure\Doctrine\Type\OptionOrderType
            answer_id: App\Question\Infrastructure\Doctrine\Type\AnswerIdType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            App:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
            Question_Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Question/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Question\Domain\Entity'
            Question_Infrastructure:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Question/Infrastructure/Doctrine/Entity'
                prefix: 'App\Question\Infrastructure\Doctrine\Entity'
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
