services:
    symfony_app:
        build:
            context: .
        ports:
            - 3310:3310
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
        depends_on:
            - mysql
        networks:
            - match-project
        hostname: symfony-app
    mysql:
        image: mysql:latest
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql:rw,z
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DB_NAME}"
        networks:
            - match-project
    pma:
        image: phpmyadmin:latest
        restart: on-failure
        ports:
            - 3311:80
        depends_on:
            - mysql
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - 'PMA_USER=${MYSQL_USER}'
            - 'PMA_PASSWORD=${MYSQL_PASSWORD}'
        networks:
            - match-project
networks:
    match-project:
        driver: bridge